development:
  adapter: postgresql
  encoding: utf8
  database: intr-api_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: intr-api_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: intr-api_production
  pool: 5
  username:
  password:
